version: "3.9"

services:
    mongo:
        image: mongo
        restart: always
        ports:
           - "27018:27017"
        
        environment:
            MONGO_INITDB_ROOT_USERNAME: "user"
            MONGO_INITDB_ROOT_PASSWORD: "pass2022"